name: Documentation
on:
  push:
    branches:
      - 'main'
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'TheDevYellowy'
    outputs:
      BRANCH_NAME: ${{ steps.env.outputs.BRANCH_NAME }}
      BRANCH_OR_TAG: ${{ steps.env.outputs.BRANCH_OR_TAG }}
      SHA: ${{ steps.env.outputs.SHA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || '' }}

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Install dependencies
        run: yarn --immutable

      - name: Build dependencies
        run: yarn build --cache-dir=".turbo"

      - name: Build docs
        run: yarn docs --cache-dir=".turbo"

      - name: Upload docgen artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docgen
          path: packages/*/docs/docs.json

      - name: Upload api-extractor artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-extractor
          path: packages/*/docs/docs.api.json

      - name: Set outputs for upload job
        id: env
        run: |
          echo "::set-output name=BRANCH_NAME::${GITHUB_REF_NAME}"
          echo "::set-output name=BRANCH_OR_TAG::${GITHUB_REF_TYPE}"
          echo "::set-output name=SHA::${GITHUB_SHA}"